import { port, ports } from "./_helpers";
import type { DeviceTemplate } from "../types";

export const templates: DeviceTemplate[] = [
  // Audio Mixer
  {
    id: "c0a80101-0005-4000-8000-000000000005",
    deviceType: "audio-mixer",
    label: "Audio Mixer",
    powerDrawW: 100, // typical
    ports: [
      port("Analog In 1", "analog-audio", "input"),
      port("Analog In 2", "analog-audio", "input"),
      port("Dante In", "dante", "input"),
      port("AES In", "aes", "input"),
      port("PGM Out", "analog-audio", "output"),
      port("AUX Out", "analog-audio", "output"),
      port("Dante Out", "dante", "output"),
      port("AES Out", "aes", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  // Audio Embedders / De-Embedders
  // BMD Teranex Mini SDI to Audio 12G — Audio De-Embedder
  {
    id: "c0a80101-0031-4000-8000-000000000049",
    deviceType: "audio-embedder",
    label: "BMD SDI→Audio 12G",
    manufacturer: "Blackmagic Design",
    modelNumber: "Teranex Mini SDI to Audio 12G",
    referenceUrl: "https://www.blackmagicdesign.com/products/teranexmini/techspecs/W-TERAMIN-05",
    searchTerms: ["blackmagic", "teranex", "de-embedder", "deembed", "audio extract"],
    powerDrawW: 16,
    heightMm: 45,
    widthMm: 140,
    depthMm: 170,
    weightKg: 0.6,
    ports: [
      port("SDI In", "sdi", "input"),
      port("SDI Loop", "sdi", "output"),
      port("Analog Out L", "analog-audio", "output"),
      port("Analog Out R", "analog-audio", "output"),
      port("AES Out 1-2", "aes", "output"),
      port("AES Out 3-4", "aes", "output"),
      port("AC Power", "power", "input"),
    
      port("S/PDIF Out", "spdif", "output", "toslink"),
    ],
  },
  // BMD Teranex Mini Audio to SDI 12G — Audio Embedder
  {
    id: "c0a80101-0032-4000-8000-000000000050",
    deviceType: "audio-embedder",
    label: "BMD Audio→SDI 12G",
    manufacturer: "Blackmagic Design",
    modelNumber: "Teranex Mini Audio to SDI 12G",
    referenceUrl: "https://www.blackmagicdesign.com/products/teranexmini/techspecs/W-TERAMIN-06",
    searchTerms: ["blackmagic", "teranex", "embedder", "audio embed"],
    powerDrawW: 16,
    heightMm: 45,
    widthMm: 140,
    depthMm: 170,
    weightKg: 0.6,
    ports: [
      port("SDI In", "sdi", "input"),
      port("Analog In L", "analog-audio", "input"),
      port("Analog In R", "analog-audio", "input"),
      port("AES In 1-2", "aes", "input"),
      port("AES In 3-4", "aes", "input"),
      port("SDI Out", "sdi", "output"),
      port("AC Power", "power", "input"),
    
      port("S/PDIF In", "spdif", "input", "toslink"),
    ],
  },
  // Wireless Microphone Receivers
  // Shure ULXD4Q — Quad Wireless Mic Receiver
  {
    id: "c0a80101-0035-4000-8000-000000000053",
    deviceType: "wireless-mic-receiver",
    label: "Shure ULXD4Q",
    manufacturer: "Shure",
    modelNumber: "ULXD4Q",
    referenceUrl: "https://www.shure.com/en-US/products/wireless-systems/ulx-d_digital_wireless/ulxd4q",
    searchTerms: ["shure", "ulx-d", "wireless", "microphone", "receiver", "quad"],
    powerDrawW: 40, // typical
    heightMm: 44,
    widthMm: 482,
    depthMm: 274,
    weightKg: 3.5,
    ports: [
      port("Analog Out 1", "analog-audio", "output"),
      port("Analog Out 2", "analog-audio", "output"),
      port("Analog Out 3", "analog-audio", "output"),
      port("Analog Out 4", "analog-audio", "output"),
      port("Dante 1", "dante", "bidirectional"),
      port("Dante 2", "dante", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("AES Out 1-2", "aes", "output"),
    
      port("AES Out 3-4", "aes", "output"),
    ],
  },
  // Sennheiser EW-DX EM 4 Dante — Quad Wireless Mic Receiver
  {
    id: "c0a80101-0036-4000-8000-000000000054",
    deviceType: "wireless-mic-receiver",
    label: "Sennheiser EW-DX EM 4",
    manufacturer: "Sennheiser",
    modelNumber: "EW-DX EM 4 Dante",
    referenceUrl: "https://www.sennheiser.com/en-us/catalog/products/wireless-systems/ew-dx-em-4-dante/ew-dx-em-4-dante-q1-9-509370",
    searchTerms: ["sennheiser", "ew-dx", "wireless", "microphone", "receiver", "dante"],
    powerDrawW: 37,
    heightMm: 44,
    widthMm: 483,
    depthMm: 373,
    weightKg: 4.6,
    ports: [
      port("Analog Out 1", "analog-audio", "output"),
      port("Analog Out 2", "analog-audio", "output"),
      port("Analog Out 3", "analog-audio", "output"),
      port("Analog Out 4", "analog-audio", "output"),
      port("Dante 1", "dante", "bidirectional"),
      port("Dante 2", "dante", "bidirectional"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  // Audio Interfaces
  // Focusrite RedNet A16R MkII — Dante Audio Interface
  {
    id: "c0a80101-0037-4000-8000-000000000055",
    deviceType: "audio-interface",
    label: "Focusrite RedNet A16R",
    manufacturer: "Focusrite",
    modelNumber: "RedNet A16R MkII",
    referenceUrl: "https://us.focusrite.com/products/rednet-a16r-mkii",
    searchTerms: ["focusrite", "rednet", "dante", "audio interface", "a16r"],
    powerDrawW: 40, // typical
    heightMm: 44,
    widthMm: 482,
    depthMm: 352,
    weightKg: 5,
    ports: [
      port("Analog In 1-8", "analog-audio", "input", "db25"),
      port("Analog In 9-16", "analog-audio", "input", "db25"),
      port("AES In", "aes", "input"),
      port("Analog Out 1-8", "analog-audio", "output", "db25"),
      port("Analog Out 9-16", "analog-audio", "output", "db25"),
      port("AES Out", "aes", "output"),
      port("Dante Primary", "dante", "bidirectional", "ethercon"),
      port("Dante Secondary", "dante", "bidirectional", "ethercon"),
      port("Word Clock In", "genlock", "input"),
      port("Word Clock Out", "genlock", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  // ── Audio Consoles ───────────────────────────────────────────────
  {
    id: "c0a80101-008b-4000-8000-000000000139",
    deviceType: "audio-mixer",
    label: "Yamaha CL5",
    manufacturer: "Yamaha",
    modelNumber: "CL5",
    referenceUrl: "https://usa.yamaha.com/products/proaudio/mixers/cl_series/index.html",
    searchTerms: ["yamaha", "cl5", "digital console", "72 channel"],
    powerDrawW: 170,
    slots: [
      { id: "cl5-my-1", label: "MY Slot 1", slotFamily: "yamaha-my" },
      { id: "cl5-my-2", label: "MY Slot 2", slotFamily: "yamaha-my" },
      { id: "cl5-my-3", label: "MY Slot 3", slotFamily: "yamaha-my" },
    ],
    heightMm: 299,
    widthMm: 1053,
    depthMm: 667,
    weightKg: 36,
    ports: [
      ...ports("OMNI In", "analog-audio", "input", 8),
      ...ports("OMNI Out", "analog-audio", "output", 8),
      port("AES In", "aes", "input"),
      port("AES Out", "aes", "output"),
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("Headphone", "analog-audio", "output", "trs-quarter"),
    
      port("Word Clock In", "genlock", "input"),
    
      port("Word Clock Out", "genlock", "output"),
    
      port("Talkback In", "analog-audio", "input"),
    ],
  },
  {
    id: "c0a80101-008c-4000-8000-000000000140",
    deviceType: "audio-mixer",
    label: "Yamaha CL3",
    manufacturer: "Yamaha",
    modelNumber: "CL3",
    referenceUrl: "https://usa.yamaha.com/products/proaudio/mixers/cl_series/index.html",
    searchTerms: ["yamaha", "cl3", "digital console", "64 channel"],
    powerDrawW: 170,
    slots: [
      { id: "cl3-my-1", label: "MY Slot 1", slotFamily: "yamaha-my" },
      { id: "cl3-my-2", label: "MY Slot 2", slotFamily: "yamaha-my" },
      { id: "cl3-my-3", label: "MY Slot 3", slotFamily: "yamaha-my" },
    ],
    heightMm: 299,
    widthMm: 839,
    depthMm: 667,
    weightKg: 29,
    ports: [
      ...ports("OMNI In", "analog-audio", "input", 8),
      ...ports("OMNI Out", "analog-audio", "output", 8),
      port("AES In", "aes", "input"),
      port("AES Out", "aes", "output"),
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("Headphone", "analog-audio", "output", "trs-quarter"),
    
      port("Word Clock In", "genlock", "input"),
    
      port("Word Clock Out", "genlock", "output"),
    
      port("Talkback In", "analog-audio", "input"),
    ],
  },
  {
    id: "c0a80101-008d-4000-8000-000000000141",
    deviceType: "audio-mixer",
    label: "Yamaha CL1",
    manufacturer: "Yamaha",
    modelNumber: "CL1",
    referenceUrl: "https://usa.yamaha.com/products/proaudio/mixers/cl_series/index.html",
    searchTerms: ["yamaha", "cl1", "digital console", "48 channel"],
    powerDrawW: 170,
    slots: [
      { id: "cl1-my-1", label: "MY Slot 1", slotFamily: "yamaha-my" },
      { id: "cl1-my-2", label: "MY Slot 2", slotFamily: "yamaha-my" },
      { id: "cl1-my-3", label: "MY Slot 3", slotFamily: "yamaha-my" },
    ],
    heightMm: 299,
    widthMm: 648,
    depthMm: 667,
    weightKg: 24,
    ports: [
      ...ports("OMNI In", "analog-audio", "input", 8),
      ...ports("OMNI Out", "analog-audio", "output", 8),
      port("AES In", "aes", "input"),
      port("AES Out", "aes", "output"),
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("Headphone", "analog-audio", "output", "trs-quarter"),
    
      port("Word Clock In", "genlock", "input"),
    
      port("Word Clock Out", "genlock", "output"),
    
      port("Talkback In", "analog-audio", "input"),
    ],
  },
  {
    id: "c0a80101-008e-4000-8000-000000000142",
    deviceType: "audio-mixer",
    label: "Yamaha QL5",
    manufacturer: "Yamaha",
    modelNumber: "QL5",
    referenceUrl: "https://usa.yamaha.com/products/proaudio/mixers/ql_series/index.html",
    searchTerms: ["yamaha", "ql5", "digital console", "32 channel"],
    powerDrawW: 200,
    slots: [
      { id: "ql5-my-1", label: "MY Slot 1", slotFamily: "yamaha-my" },
      { id: "ql5-my-2", label: "MY Slot 2", slotFamily: "yamaha-my" },
    ],
    heightMm: 272,
    widthMm: 828,
    depthMm: 563,
    weightKg: 21.8,
    ports: [
      ...ports("Analog In", "analog-audio", "input", 32),
      ...ports("Analog Out", "analog-audio", "output", 8),
      port("AES In", "aes", "input"),
      port("AES Out", "aes", "output"),
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("Headphone", "analog-audio", "output", "trs-quarter"),
    
      port("Word Clock In", "genlock", "input"),
    
      port("Word Clock Out", "genlock", "output"),
    ],
  },
  {
    id: "c0a80101-008f-4000-8000-000000000143",
    deviceType: "audio-mixer",
    label: "Yamaha QL1",
    manufacturer: "Yamaha",
    modelNumber: "QL1",
    referenceUrl: "https://usa.yamaha.com/products/proaudio/mixers/ql_series/index.html",
    searchTerms: ["yamaha", "ql1", "digital console", "16 channel"],
    powerDrawW: 135,
    slots: [
      { id: "ql1-my-1", label: "MY Slot 1", slotFamily: "yamaha-my" },
      { id: "ql1-my-2", label: "MY Slot 2", slotFamily: "yamaha-my" },
    ],
    heightMm: 272,
    widthMm: 468,
    depthMm: 562,
    weightKg: 14.7,
    ports: [
      ...ports("Analog In", "analog-audio", "input", 16),
      ...ports("Analog Out", "analog-audio", "output", 8),
      port("AES In", "aes", "input"),
      port("AES Out", "aes", "output"),
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("Headphone", "analog-audio", "output", "trs-quarter"),
    
      port("Word Clock In", "genlock", "input"),
    
      port("Word Clock Out", "genlock", "output"),
    ],
  },
  {
    id: "c0a80101-0090-4000-8000-000000000144",
    deviceType: "audio-mixer",
    label: "Yamaha TF5",
    manufacturer: "Yamaha",
    modelNumber: "TF5",
    referenceUrl: "https://usa.yamaha.com/products/proaudio/mixers/tf/index.html",
    searchTerms: ["yamaha", "tf5", "digital console", "32 channel", "touchflow"],
    powerDrawW: 120,
    heightMm: 225,
    widthMm: 866,
    depthMm: 599,
    weightKg: 20,
    ports: [
      ...ports("Analog In", "analog-audio", "input", 32),
      ...ports("Analog Out", "analog-audio", "output", 16),
      port("Dante", "dante", "bidirectional"),
      port("USB", "usb", "bidirectional"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("RCA In L", "analog-audio", "input", "rca"),
    
      port("RCA In R", "analog-audio", "input", "rca"),
    
      port("Headphone", "analog-audio", "output", "trs-quarter"),
    ],
  },
  {
    id: "c0a80101-0091-4000-8000-000000000145",
    deviceType: "audio-mixer",
    label: "Yamaha TF3",
    manufacturer: "Yamaha",
    modelNumber: "TF3",
    referenceUrl: "https://usa.yamaha.com/products/proaudio/mixers/tf/index.html",
    searchTerms: ["yamaha", "tf3", "digital console", "24 channel"],
    powerDrawW: 110,
    heightMm: 225,
    widthMm: 716,
    depthMm: 599,
    weightKg: 17,
    ports: [
      ...ports("Analog In", "analog-audio", "input", 24),
      ...ports("Analog Out", "analog-audio", "output", 16),
      port("Dante", "dante", "bidirectional"),
      port("USB", "usb", "bidirectional"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("RCA In L", "analog-audio", "input", "rca"),
    
      port("RCA In R", "analog-audio", "input", "rca"),
    
      port("Headphone", "analog-audio", "output", "trs-quarter"),
    ],
  },
  {
    id: "c0a80101-0092-4000-8000-000000000146",
    deviceType: "audio-mixer",
    label: "Yamaha TF1",
    manufacturer: "Yamaha",
    modelNumber: "TF1",
    referenceUrl: "https://usa.yamaha.com/products/proaudio/mixers/tf/index.html",
    searchTerms: ["yamaha", "tf1", "digital console", "16 channel"],
    powerDrawW: 100,
    heightMm: 225,
    widthMm: 510,
    depthMm: 599,
    weightKg: 13.5,
    ports: [
      ...ports("Analog In", "analog-audio", "input", 16),
      ...ports("Analog Out", "analog-audio", "output", 16),
      port("Dante", "dante", "bidirectional"),
      port("USB", "usb", "bidirectional"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("RCA In L", "analog-audio", "input", "rca"),
    
      port("RCA In R", "analog-audio", "input", "rca"),
    
      port("Headphone", "analog-audio", "output", "trs-quarter"),
    ],
  },
  {
    id: "c0a80101-0093-4000-8000-000000000147",
    version: 2, // v2: SLink-as-fiber ports corrected to gigaACE + DX
    deviceType: "audio-mixer",
    label: "A&H dLive S7000",
    manufacturer: "Allen & Heath",
    modelNumber: "dLive S7000",
    referenceUrl: "https://www.allen-heath.com/hardware/dlive/dlive-s-class/s7000/",
    searchTerms: ["allen heath", "dlive", "s7000", "digital console"],
    powerDrawW: 350, // typical
    slots: [
      { id: "dlive-io-1", label: "I/O Port 1", slotFamily: "ah-dlive-io" },
      { id: "dlive-io-2", label: "I/O Port 2", slotFamily: "ah-dlive-io" },
      { id: "dlive-io-3", label: "I/O Port 3", slotFamily: "ah-dlive-io" },
    ],
    heightMm: 413,
    widthMm: 1325,
    depthMm: 729,
    weightKg: 41,
    ports: [
      port("gigaACE Primary", "gigaace", "bidirectional"),
      port("gigaACE Secondary", "gigaace", "bidirectional"),
      port("DX 1", "dx5", "bidirectional"),
      port("DX 2", "dx5", "bidirectional"),
      port("Word Clock", "genlock", "bidirectional"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("AES In 1", "aes", "input"),
    
      port("AES In 2", "aes", "input"),
    
      port("AES Out 1", "aes", "output"),
    
      port("AES Out 2", "aes", "output"),
    
      port("AES Out 3", "aes", "output"),
    
      port("Analog In 1", "analog-audio", "input"),
    
      port("Analog In 2", "analog-audio", "input"),
    
      port("Analog In 3", "analog-audio", "input"),
    
      port("Analog In 4", "analog-audio", "input"),
    
      port("Analog In 5", "analog-audio", "input"),
    
      port("Analog In 6", "analog-audio", "input"),
    
      port("Analog In 7", "analog-audio", "input"),
    
      port("Analog In 8", "analog-audio", "input"),
    
      port("Analog Out 1", "analog-audio", "output"),
    
      port("Analog Out 2", "analog-audio", "output"),
    
      port("Analog Out 3", "analog-audio", "output"),
    
      port("Analog Out 4", "analog-audio", "output"),
    
      port("Analog Out 5", "analog-audio", "output"),
    
      port("Analog Out 6", "analog-audio", "output"),
    
      port("Analog Out 7", "analog-audio", "output"),
    
      port("Analog Out 8", "analog-audio", "output"),
    ],
  },
  {
    id: "c0a80101-0094-4000-8000-000000000148",
    version: 2, // v2: SLink port signal corrected fiber → slink
    deviceType: "audio-mixer",
    label: "A&H SQ-7",
    manufacturer: "Allen & Heath",
    modelNumber: "SQ-7",
    referenceUrl: "https://www.allen-heath.com/hardware/sq/sq-7/",
    searchTerms: ["allen heath", "sq7", "digital console", "32 channel"],
    powerDrawW: 120, // typical
    slots: [
      { id: "sq7-slink-exp", label: "SLink Expansion", slotFamily: "ah-sq-slink" },
    ],
    heightMm: 198,
    widthMm: 804,
    depthMm: 515,
    weightKg: 17.8,
    ports: [
      ...ports("Analog In", "analog-audio", "input", 32),
      ...ports("Analog Out", "analog-audio", "output", 12),
      port("SLink", "slink", "bidirectional"),
      port("USB", "usb", "bidirectional"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("AES Out", "aes", "output"),
    
      port("ST1 In L", "analog-audio", "input", "trs-quarter"),
    
      port("ST1 In R", "analog-audio", "input", "trs-quarter"),
    
      port("ST2 In L", "analog-audio", "input", "trs-quarter"),
    
      port("ST2 In R", "analog-audio", "input", "trs-quarter"),
    
      port("ST3 In", "analog-audio", "input", "trs-eighth"),
    
      port("Headphone", "analog-audio", "output", "trs-quarter"),
    ],
  },
  {
    id: "c0a80101-0095-4000-8000-000000000149",
    version: 2, // v2: SLink port signal corrected fiber → slink
    deviceType: "audio-mixer",
    label: "A&H SQ-5",
    manufacturer: "Allen & Heath",
    modelNumber: "SQ-5",
    referenceUrl: "https://www.allen-heath.com/hardware/sq/sq-5/",
    searchTerms: ["allen heath", "sq5", "digital console", "16 channel"],
    powerDrawW: 100, // typical
    slots: [
      { id: "sq5-slink-exp", label: "SLink Expansion", slotFamily: "ah-sq-slink" },
    ],
    heightMm: 198,
    widthMm: 440,
    depthMm: 515,
    weightKg: 10.5,
    ports: [
      ...ports("Analog In", "analog-audio", "input", 16),
      ...ports("Analog Out", "analog-audio", "output", 12),
      port("SLink", "slink", "bidirectional"),
      port("USB", "usb", "bidirectional"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("AES Out", "aes", "output"),
    
      port("ST1 In L", "analog-audio", "input", "trs-quarter"),
    
      port("ST1 In R", "analog-audio", "input", "trs-quarter"),
    
      port("ST2 In L", "analog-audio", "input", "trs-quarter"),
    
      port("ST2 In R", "analog-audio", "input", "trs-quarter"),
    
      port("ST3 In", "analog-audio", "input", "trs-eighth"),
    
      port("Headphone", "analog-audio", "output", "trs-quarter"),
    ],
  },
  {
    id: "c0a80101-0096-4000-8000-000000000150",
    deviceType: "audio-mixer",
    label: "DiGiCo SD7",
    manufacturer: "DiGiCo",
    modelNumber: "SD7",
    referenceUrl: "https://digico.biz/consoles/sd7/",
    searchTerms: ["digico", "sd7", "digital console", "flagship"],
    powerDrawW: 600, // typical
    slots: [
      { id: "sd7-dmi-1", label: "DMI Slot 1", slotFamily: "digico-dmi" },
      { id: "sd7-dmi-2", label: "DMI Slot 2", slotFamily: "digico-dmi" },
    ],
    heightMm: 503,
    widthMm: 1496,
    depthMm: 875,
    weightKg: 141,
    ports: [
      port("MADI 1", "madi", "bidirectional"),
      port("MADI 2", "madi", "bidirectional"),
      port("MADI 3", "madi", "bidirectional"),
      port("Optocore 1", "fiber", "bidirectional"),
      port("Optocore 2", "fiber", "bidirectional"),
      port("Dante", "dante", "bidirectional"),
      port("AES In", "aes", "input"),
      port("AES Out", "aes", "output"),
      port("Word Clock", "genlock", "bidirectional"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("Analog In 1", "analog-audio", "input"),
    
      port("Analog In 2", "analog-audio", "input"),
    
      port("Analog In 3", "analog-audio", "input"),
    
      port("Analog In 4", "analog-audio", "input"),
    
      port("Analog In 5", "analog-audio", "input"),
    
      port("Analog In 6", "analog-audio", "input"),
    
      port("Analog In 7", "analog-audio", "input"),
    
      port("Analog In 8", "analog-audio", "input"),
    
      port("Analog In 9", "analog-audio", "input"),
    
      port("Analog In 10", "analog-audio", "input"),
    
      port("Analog In 11", "analog-audio", "input"),
    
      port("Analog In 12", "analog-audio", "input"),
    
      port("Analog Out 1", "analog-audio", "output"),
    
      port("Analog Out 2", "analog-audio", "output"),
    
      port("Analog Out 3", "analog-audio", "output"),
    
      port("Analog Out 4", "analog-audio", "output"),
    
      port("Analog Out 5", "analog-audio", "output"),
    
      port("Analog Out 6", "analog-audio", "output"),
    
      port("Analog Out 7", "analog-audio", "output"),
    
      port("Analog Out 8", "analog-audio", "output"),
    
      port("Analog Out 9", "analog-audio", "output"),
    
      port("Analog Out 10", "analog-audio", "output"),
    
      port("Analog Out 11", "analog-audio", "output"),
    
      port("Analog Out 12", "analog-audio", "output"),
    ],
  },
  {
    id: "c0a80101-011a-4000-8000-000000000358",
    deviceType: "audio-mixer",
    label: "DiGiCo SD12",
    manufacturer: "DiGiCo",
    modelNumber: "SD12",
    referenceUrl: "https://digico.biz/consoles/sd12/",
    searchTerms: ["digico", "sd12", "digital console"],
    powerDrawW: 250, // typical
    slots: [
      { id: "sd12-dmi-1", label: "DMI Slot 1", slotFamily: "digico-dmi" },
      { id: "sd12-dmi-2", label: "DMI Slot 2", slotFamily: "digico-dmi" },
    ],
    heightMm: 389,
    widthMm: 1124,
    depthMm: 795,
    weightKg: 42,
    ports: [
      port("MADI 1", "madi", "bidirectional"),
      port("Optocore 1", "fiber", "bidirectional"),
      port("Optocore 2", "fiber", "bidirectional"),
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
      port("AES In", "aes", "input"),
      port("AES Out", "aes", "output"),
      port("Word Clock", "genlock", "bidirectional"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  // ── Audio Stage Boxes & DSP ──────────────────────────────────────
  {
    id: "c0a80101-0097-4000-8000-000000000151",
    deviceType: "stage-box",
    label: "Yamaha Rio3224-D2",
    manufacturer: "Yamaha",
    modelNumber: "Rio3224-D2",
    referenceUrl: "https://usa.yamaha.com/products/proaudio/interfaces/rio3224-d2/index.html",
    searchTerms: ["yamaha", "rio", "stage box", "dante", "32 channel"],
    powerDrawW: 85, // typical
    heightMm: 220,
    widthMm: 480,
    depthMm: 368,
    weightKg: 13.5,
    ports: [
      ...ports("Analog In", "analog-audio", "input", 32),
      ...ports("Analog Out", "analog-audio", "output", 24),
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
      port("Word Clock In", "genlock", "input"),
      port("Word Clock Out", "genlock", "output"),
      port("AC Power", "power", "input"),
    
      port("AES In", "aes", "input"),
    
      port("AES Out", "aes", "output"),
    ],
  },
  {
    id: "c0a80101-0098-4000-8000-000000000152",
    deviceType: "stage-box",
    label: "Yamaha Rio1608-D",
    manufacturer: "Yamaha",
    modelNumber: "Rio1608-D",
    referenceUrl: "https://usa.yamaha.com/products/proaudio/interfaces/rio1608-d2/index.html",
    searchTerms: ["yamaha", "rio", "stage box", "dante", "16 channel"],
    powerDrawW: 55, // typical
    heightMm: 144,
    widthMm: 480,
    depthMm: 362,
    weightKg: 8.8,
    ports: [
      ...ports("Analog In", "analog-audio", "input", 16),
      ...ports("Analog Out", "analog-audio", "output", 8),
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0099-4000-8000-000000000153",
    deviceType: "audio-dsp",
    label: "QSC Q-SYS Core 110f",
    manufacturer: "QSC",
    modelNumber: "Core 110f",
    referenceUrl: "https://www.qsc.com/resource-files/productresources/dsp/q-sys_core/q_qsc_core_110f_spec.pdf",
    searchTerms: ["qsc", "q-sys", "core", "dsp", "audio processor"],
    powerDrawW: 60, // typical
    heightMm: 44,
    widthMm: 483,
    depthMm: 283,
    weightKg: 5,
    ports: [
      ...ports("Analog In", "analog-audio", "input", 8, "phoenix"),
      ...ports("Analog Out", "analog-audio", "output", 8, "phoenix"),
      port("AES In", "aes", "input", "phoenix"),
      port("AES Out", "aes", "output", "phoenix"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
      port("RS-232", "serial", "bidirectional", "phoenix"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-009a-4000-8000-000000000154",
    deviceType: "audio-dsp",
    label: "Biamp Tesira SERVER",
    manufacturer: "Biamp",
    modelNumber: "Tesira SERVER",
    referenceUrl: "https://www.biamp.com/products/tesira-platform",
    searchTerms: ["biamp", "tesira", "server", "dsp", "avb"],
    powerDrawW: 100, // typical
    heightMm: 133,
    widthMm: 483,
    depthMm: 432,
    weightKg: 8.2,
    ports: [
      ...ports("Analog In", "analog-audio", "input", 12, "phoenix"),
      ...ports("Analog Out", "analog-audio", "output", 8, "phoenix"),
      ...ports("AES In", "aes", "input", 8),
      ...ports("AES Out", "aes", "output", 8),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-009b-4000-8000-000000000155",
    deviceType: "audio-interface",
    label: "Focusrite RedNet PCIeNX",
    manufacturer: "Focusrite",
    modelNumber: "RedNet PCIeNX",
    referenceUrl: "https://us.focusrite.com/products/rednet-pcienx",
    searchTerms: ["focusrite", "rednet", "pcie", "dante", "card"],
    powerDrawW: 7, // typical (PCIe bus powered)
    ports: [
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
    ],
  },
  {
    id: "c0a80101-009c-4000-8000-000000000156",
    deviceType: "audio-interface",
    label: "Audinate AVIO Input",
    manufacturer: "Audinate",
    modelNumber: "AVIO Analog Input 2ch",
    referenceUrl: "https://www.audinate.com/products/devices/dante-avio",
    searchTerms: ["audinate", "avio", "dante", "analog input", "adapter"],
    powerDrawW: 5, // typical (PoE powered)
    heightMm: 28,
    widthMm: 35,
    depthMm: 114,
    weightKg: 0.1,
    ports: [
      port("Analog In 1", "analog-audio", "input", "phoenix"),
      port("Analog In 2", "analog-audio", "input", "phoenix"),
      port("Ethernet", "ethernet", "bidirectional"),
    ],
  },
  {
    id: "c0a80101-009d-4000-8000-000000000157",
    deviceType: "audio-interface",
    label: "Audinate AVIO Output",
    manufacturer: "Audinate",
    modelNumber: "AVIO Analog Output 2ch",
    referenceUrl: "https://www.audinate.com/products/devices/dante-avio",
    searchTerms: ["audinate", "avio", "dante", "analog output", "adapter"],
    powerDrawW: 5, // typical (PoE powered)
    heightMm: 28,
    widthMm: 35,
    depthMm: 114,
    weightKg: 0.1,
    ports: [
      port("Analog Out 1", "analog-audio", "output", "phoenix"),
      port("Analog Out 2", "analog-audio", "output", "phoenix"),
      port("Ethernet", "ethernet", "bidirectional"),
    ],
  },
  {
    id: "c0a80101-009e-4000-8000-000000000158",
    deviceType: "audio-interface",
    label: "Audinate AVIO USB",
    manufacturer: "Audinate",
    modelNumber: "AVIO USB",
    referenceUrl: "https://www.audinate.com/products/devices/dante-avio",
    searchTerms: ["audinate", "avio", "dante", "usb"],
    powerDrawW: 5, // typical (PoE powered)
    heightMm: 28,
    widthMm: 35,
    depthMm: 114,
    weightKg: 0.1,
    ports: [
      port("USB", "usb", "bidirectional"),
      port("Ethernet", "ethernet", "bidirectional"),
    ],
  },
  // ── Wireless Mics ────────────────────────────────────────────────
  {
    id: "c0a80101-009f-4000-8000-000000000159",
    deviceType: "wireless-mic-receiver",
    label: "Shure AD4Q",
    manufacturer: "Shure",
    modelNumber: "AD4Q",
    referenceUrl: "https://www.shure.com/en-US/products/wireless-systems/axient_digital/ad4q",
    searchTerms: ["shure", "axient", "digital", "quad", "wireless", "receiver"],
    powerDrawW: 50, // typical
    heightMm: 44,
    widthMm: 483,
    depthMm: 333,
    weightKg: 4.8,
    ports: [
      ...ports("Analog Out", "analog-audio", "output", 4),
      port("AES Out", "aes", "output"),
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-00a0-4000-8000-000000000160",
    deviceType: "wireless-mic-receiver",
    label: "Shure QLXD4",
    manufacturer: "Shure",
    modelNumber: "QLXD4",
    referenceUrl: "https://www.shure.com/en-US/products/wireless-systems/qlx-d/qlxd4",
    searchTerms: ["shure", "qlx-d", "wireless", "receiver"],
    powerDrawW: 12, // typical
    heightMm: 41,
    widthMm: 197,
    depthMm: 151,
    weightKg: 0.8,
    ports: [
      port("Analog Out", "analog-audio", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-00a1-4000-8000-000000000161",
    deviceType: "wireless-mic-receiver",
    label: "Shure SLXD4",
    manufacturer: "Shure",
    modelNumber: "SLXD4",
    referenceUrl: "https://www.shure.com/en-US/products/wireless-systems/slx-d/slxd4",
    searchTerms: ["shure", "slx-d", "wireless", "receiver"],
    powerDrawW: 12, // typical
    heightMm: 42,
    widthMm: 197,
    depthMm: 152,
    weightKg: 0.8,
    ports: [
      port("Analog Out", "analog-audio", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-00a2-4000-8000-000000000162",
    deviceType: "wireless-mic-receiver",
    label: "Sennheiser EM 6000",
    manufacturer: "Sennheiser",
    modelNumber: "EM 6000",
    referenceUrl: "https://www.sennheiser.com/en-us/catalog/products/wireless-systems/digital-6000/digital-6000-em-6000-509360",
    searchTerms: ["sennheiser", "digital 6000", "wireless", "receiver"],
    powerDrawW: 30, // typical
    heightMm: 44,
    widthMm: 483,
    depthMm: 373,
    weightKg: 5.2,
    ports: [
      port("Analog Out 1", "analog-audio", "output"),
      port("Analog Out 2", "analog-audio", "output"),
      port("AES Out", "aes", "output"),
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("Word Clock In", "genlock", "input"),
    
      port("Word Clock Out", "genlock", "output"),
    ],
  },
  {
    id: "c0a80101-00b2-4000-8000-000000000178",
    deviceType: "audio-dsp",
    label: "Meyer Galileo Galaxy 816",
    manufacturer: "Meyer Sound",
    modelNumber: "Galileo Galaxy 816",
    referenceUrl: "https://meyersound.com/product/galileo-galaxy-816/",
    searchTerms: ["meyer", "galileo", "galaxy", "816", "processor"],
    powerDrawW: 80, // typical
    heightMm: 88,
    widthMm: 483,
    depthMm: 410,
    weightKg: 7.6,
    ports: [
      ...ports("Analog In", "analog-audio", "input", 8),
      ...ports("Analog Out", "analog-audio", "output", 16),
      port("AES In", "aes", "input"),
      port("AES Out", "aes", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("Headphone", "analog-audio", "output", "trs-quarter"),
    ],
  },
  // Audio new devices
  {
    id: "c0a80101-0107-4000-8000-000000000339",
    deviceType: "audio-mixer",
    category: "audio-mixers",
    label: "Yamaha DM7",
    manufacturer: "Yamaha",
    modelNumber: "DM7",
    referenceUrl: "https://usa.yamaha.com/products/proaudio/mixers/dm7/index.html",
    searchTerms: ["yamaha", "dm7", "digital console"],
    powerDrawW: 150, // typical
    heightMm: 324,
    widthMm: 793,
    depthMm: 564,
    weightKg: 23.5,
    ports: [
      ...ports("Analog In", "analog-audio", "input", 16),
      ...ports("Analog Out", "analog-audio", "output", 8),
      port("AES Out", "aes", "output"),
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
      port("USB", "usb", "bidirectional", "usb-c"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0108-4000-8000-000000000340",
    deviceType: "audio-interface",
    category: "audio-interfaces",
    label: "Shure ANI4IN",
    manufacturer: "Shure",
    modelNumber: "ANI4IN-XLR",
    referenceUrl: "https://www.shure.com/en-US/products/mixers/ani/ani4in-xlr",
    searchTerms: ["shure", "ani", "dante", "audio network interface", "4 input"],
    powerDrawW: 5, // typical (PoE powered)
    heightMm: 43,
    widthMm: 165,
    depthMm: 127,
    weightKg: 0.7,
    ports: [
      port("Analog In 1", "analog-audio", "input"),
      port("Analog In 2", "analog-audio", "input"),
      port("Analog In 3", "analog-audio", "input"),
      port("Analog In 4", "analog-audio", "input"),
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
    ],
  },
  {
    id: "c0a80101-0109-4000-8000-000000000341",
    deviceType: "audio-interface",
    category: "audio-interfaces",
    label: "Shure ANI4OUT",
    manufacturer: "Shure",
    modelNumber: "ANI4OUT-XLR",
    referenceUrl: "https://www.shure.com/en-US/products/mixers/ani/ani4out-xlr",
    searchTerms: ["shure", "ani", "dante", "audio network interface", "4 output"],
    powerDrawW: 5, // typical (PoE powered)
    heightMm: 40,
    widthMm: 140,
    depthMm: 128,
    weightKg: 0.7,
    ports: [
      port("Analog Out 1", "analog-audio", "output"),
      port("Analog Out 2", "analog-audio", "output"),
      port("Analog Out 3", "analog-audio", "output"),
      port("Analog Out 4", "analog-audio", "output"),
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
    ],
  },
  // ── Yamaha Rivage PM3 / CS-R3 ──────────────────────────────────────
  {
    id: "c0a80101-01aa-4000-8000-000000000426",
    deviceType: "audio-mixer",
    label: "Yamaha CS-R3",
    manufacturer: "Yamaha",
    modelNumber: "CS-R3",
    referenceUrl:
      "https://usa.yamaha.com/products/proaudio/mixers/rivage_pm/specs.html",
    searchTerms: [
      "yamaha",
      "rivage",
      "pm3",
      "cs-r3",
      "digital console",
      "96khz",
    ],
    powerDrawW: 350, // typical
    slots: [
      { id: "csr3-hy-1", label: "HY Slot 1", slotFamily: "yamaha-hy" },
      { id: "csr3-hy-2", label: "HY Slot 2", slotFamily: "yamaha-hy" },
      { id: "csr3-hy-3", label: "HY Slot 3", slotFamily: "yamaha-hy" },
      { id: "csr3-hy-4", label: "HY Slot 4", slotFamily: "yamaha-hy" },
      { id: "csr3-my-1", label: "MY Slot 1", slotFamily: "yamaha-my" },
      { id: "csr3-my-2", label: "MY Slot 2", slotFamily: "yamaha-my" },
      { id: "csr3-my-3", label: "MY Slot 3", slotFamily: "yamaha-my" },
      { id: "csr3-my-4", label: "MY Slot 4", slotFamily: "yamaha-my" },
    ],
    heightMm: 385,
    widthMm: 1145,
    depthMm: 650,
    weightKg: 38,
    ports: [
      ...ports("Analog In", "analog-audio", "input", 8),
      ...ports("Analog Out", "analog-audio", "output", 8),
      port("GPI", "gpio", "bidirectional"),
      port("MIDI In", "midi", "input", "din-5"),
      port("MIDI Out", "midi", "output", "din-5"),
      port("USB", "usb", "bidirectional", "usb-a"),
      port("Headphone", "analog-audio", "output", "trs-quarter"),
      port("AC Power 1", "power", "input"),
      port("AC Power 2", "power", "input"),
    ],
  },
  // ── Yamaha Rivage PM5 / CS-R5 ──────────────────────────────────────
  {
    id: "c0a80101-01ab-4000-8000-000000000427",
    deviceType: "audio-mixer",
    label: "Yamaha CS-R5",
    manufacturer: "Yamaha",
    modelNumber: "CS-R5",
    referenceUrl:
      "https://usa.yamaha.com/products/proaudio/mixers/rivage_pm/specs.html",
    searchTerms: [
      "yamaha",
      "rivage",
      "pm5",
      "cs-r5",
      "digital console",
      "96khz",
    ],
    powerDrawW: 400, // typical
    slots: [
      { id: "csr5-hy-1", label: "HY Slot 1", slotFamily: "yamaha-hy" },
      { id: "csr5-hy-2", label: "HY Slot 2", slotFamily: "yamaha-hy" },
      { id: "csr5-hy-3", label: "HY Slot 3", slotFamily: "yamaha-hy" },
      { id: "csr5-hy-4", label: "HY Slot 4", slotFamily: "yamaha-hy" },
      { id: "csr5-my-1", label: "MY Slot 1", slotFamily: "yamaha-my" },
      { id: "csr5-my-2", label: "MY Slot 2", slotFamily: "yamaha-my" },
      { id: "csr5-my-3", label: "MY Slot 3", slotFamily: "yamaha-my" },
      { id: "csr5-my-4", label: "MY Slot 4", slotFamily: "yamaha-my" },
    ],
    heightMm: 414,
    widthMm: 1444,
    depthMm: 643,
    weightKg: 42,
    ports: [
      ...ports("Analog In", "analog-audio", "input", 8),
      ...ports("Analog Out", "analog-audio", "output", 8),
      ...ports("AES In", "aes", "input", 4),
      ...ports("AES Out", "aes", "output", 4),
      port("GPI", "gpio", "bidirectional"),
      port("Word Clock Out", "genlock", "output"),
      port("MIDI In", "midi", "input", "din-5"),
      port("MIDI Out", "midi", "output", "din-5"),
      port("USB", "usb", "bidirectional", "usb-a"),
      port("Headphone 1", "analog-audio", "output", "trs-quarter"),
      port("Headphone 2", "analog-audio", "output", "trs-quarter"),
      port("AC Power 1", "power", "input"),
      port("AC Power 2", "power", "input"),
    ],
  },
  // ── Yamaha DM3-D ───────────────────────────────────────────────────
  {
    id: "c0a80101-01ac-4000-8000-000000000428",
    deviceType: "audio-mixer",
    label: "Yamaha DM3-D",
    manufacturer: "Yamaha",
    modelNumber: "DM3-D",
    referenceUrl:
      "https://usa.yamaha.com/products/proaudio/mixers/dm3/specs.html",
    searchTerms: [
      "yamaha",
      "dm3",
      "dm3-d",
      "digital mixer",
      "dante",
      "compact",
    ],
    powerDrawW: 40, // typical
    heightMm: 140,
    widthMm: 320,
    depthMm: 455,
    weightKg: 6.5,
    ports: [
      ...ports("Mic/Line In", "analog-audio", "input", 12),
      ...ports("Mic/Line In", "analog-audio", "input", 4, "combo-xlr-trs"),
      ...ports("Analog Out", "analog-audio", "output", 8),
      port("Dante Primary", "dante", "bidirectional", "ethercon"),
      port("Dante Secondary", "dante", "bidirectional", "ethercon"),
      port("USB to Host", "usb", "bidirectional", "usb-b"),
      port("USB to Device", "usb", "bidirectional", "usb-a"),
      port("Ethernet", "ethernet", "bidirectional", "rj45"),
      port("Headphone", "analog-audio", "output", "trs-quarter"),
      port("DC Power", "power", "input"),
    ],
  },
  // ── Behringer X32 Compact ──────────────────────────────────────────
  {
    id: "c0a80101-01ad-4000-8000-000000000429",
    deviceType: "audio-mixer",
    label: "Behringer X32 Compact",
    manufacturer: "Behringer",
    modelNumber: "X32 Compact",
    referenceUrl:
      "https://www.behringer.com/product.html?modelCode=0603-AAB",
    searchTerms: [
      "behringer",
      "x32",
      "compact",
      "digital mixer",
      "midas preamp",
    ],
    powerDrawW: 80, // typical
    heightMm: 215,
    widthMm: 625,
    depthMm: 510,
    weightKg: 15.4,
    ports: [
      ...ports("Mic/Line In", "analog-audio", "input", 16),
      ...ports("Aux In", "analog-audio", "input", 6, "trs-quarter"),
      ...ports("XLR Out", "analog-audio", "output", 8),
      ...ports("Aux Out", "analog-audio", "output", 6, "trs-quarter"),
      port("AES50 A", "aes50", "bidirectional", "ethercon"),
      port("AES50 B", "aes50", "bidirectional", "ethercon"),
      port("AES/EBU Out", "aes", "output"),
      port("USB Card", "usb", "bidirectional", "usb-a"),
      port("Ultranet", "ultranet", "output", "rj45"),
      port("MIDI In", "midi", "input", "din-5"),
      port("MIDI Out", "midi", "output", "din-5"),
      port("Ethernet", "ethernet", "bidirectional", "rj45"),
      port("Headphone 1", "analog-audio", "output", "trs-quarter"),
      port("Headphone 2", "analog-audio", "output", "trs-quarter"),
      port("AC Power", "power", "input"),
    ],
  },
  // ── Mackie ProFX16v2 ──────────────────────────────────────────────
  {
    id: "c0a80101-01ae-4000-8000-000000000430",
    deviceType: "audio-mixer",
    label: "Mackie ProFX16v2",
    manufacturer: "Mackie",
    modelNumber: "ProFX16v2",
    referenceUrl:
      "https://mackie.com/products/discontinued/profxv2-effects-mixers",
    searchTerms: [
      "mackie",
      "profx16",
      "profx16v2",
      "analog mixer",
      "usb",
      "effects",
    ],
    powerDrawW: 50, // typical
    heightMm: 97,
    widthMm: 475,
    depthMm: 407,
    weightKg: 5.9,
    ports: [
      ...ports("Mic/Line In", "analog-audio", "input", 12, "combo-xlr-trs"),
      ...ports("Stereo In", "analog-audio", "input", 4, "trs-quarter"),
      port("Main Out L", "analog-audio", "output"),
      port("Main Out R", "analog-audio", "output"),
      port("Sub Out", "analog-audio", "output", "trs-quarter"),
      ...ports("Aux Send", "analog-audio", "output", 3, "trs-quarter"),
      port("Control Room L", "analog-audio", "output", "trs-quarter"),
      port("Control Room R", "analog-audio", "output", "trs-quarter"),
      port("USB", "usb", "bidirectional", "usb-b"),
      port("Headphone", "analog-audio", "output", "trs-quarter"),
      port("AC Power", "power", "input"),
    ],
  },
  // ── Shure Axient Digital AD4Q ─────────────────────────────────────
  {
    id: "c0a80101-01af-4000-8000-000000000431",
    deviceType: "wireless-mic-receiver",
    label: "Shure AD4Q",
    manufacturer: "Shure",
    modelNumber: "AD4Q",
    referenceUrl:
      "https://www.shure.com/en-US/products/wireless-systems/axient_digital/ad4q",
    searchTerms: [
      "shure",
      "axient",
      "digital",
      "wireless",
      "receiver",
      "quad",
      "ad4q",
    ],
    powerDrawW: 50, // typical
    heightMm: 44,
    widthMm: 483,
    depthMm: 333,
    weightKg: 4.8,
    ports: [
      port("Analog Out 1", "analog-audio", "output"),
      port("Analog Out 2", "analog-audio", "output"),
      port("Analog Out 3", "analog-audio", "output"),
      port("Analog Out 4", "analog-audio", "output"),
      port("AES3 Out 1-2", "aes", "output"),
      port("AES3 Out 3-4", "aes", "output"),
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("Word Clock", "genlock", "bidirectional", "bnc"),
      port("AC Power", "power", "input"),
    ],
  },
  // ── Shure PSM 1000 P10T ──────────────────────────────────────────
  {
    id: "c0a80101-01b0-4000-8000-000000000432",
    deviceType: "iem-transmitter",
    label: "Shure PSM 1000 P10T",
    manufacturer: "Shure",
    modelNumber: "P10T",
    referenceUrl:
      "https://www.shure.com/en-US/products/in-ear-monitoring/psm1000/p10t",
    searchTerms: [
      "shure",
      "psm",
      "1000",
      "p10t",
      "iem",
      "in-ear",
      "monitor",
      "transmitter",
    ],
    powerDrawW: 18, // typical
    heightMm: 44,
    widthMm: 483,
    depthMm: 343,
    weightKg: 4.7,
    ports: [
      port("Audio In 1", "analog-audio", "input", "combo-xlr-trs"),
      port("Audio In 2", "analog-audio", "input", "combo-xlr-trs"),
      port("Loop Out 1", "analog-audio", "output", "trs-quarter"),
      port("Loop Out 2", "analog-audio", "output", "trs-quarter"),
      port("Headphone", "analog-audio", "output", "trs-quarter"),
      port("Ethernet 1", "ethernet", "bidirectional", "rj45"),
      port("Ethernet 2", "ethernet", "bidirectional", "rj45"),
      port("AC Power", "power", "input"),
    ],
  },
  // ── Shure KSM32 ──────────────────────────────────────────────────
  {
    id: "c0a80101-01b1-4000-8000-000000000433",
    deviceType: "wired-mic",
    label: "Shure KSM32",
    manufacturer: "Shure",
    modelNumber: "KSM32",
    referenceUrl:
      "https://www.shure.com/en-US/products/microphones/ksm32c",
    searchTerms: [
      "shure",
      "ksm32",
      "condenser",
      "cardioid",
      "microphone",
      "studio",
    ],
    powerDrawW: 0,
    heightMm: 188,
    widthMm: 56,
    depthMm: 56,
    weightKg: 0.5,
    ports: [port("XLR Out", "analog-audio", "output", "xlr-3")],
  },
  // ── Shure Beta 87A ────────────────────────────────────────────────
  {
    id: "c0a80101-01b2-4000-8000-000000000434",
    deviceType: "wired-mic",
    label: "Shure Beta 87A",
    manufacturer: "Shure",
    modelNumber: "Beta 87A",
    referenceUrl:
      "https://www.shure.com/en-US/products/microphones/beta_87a",
    searchTerms: [
      "shure",
      "beta",
      "87a",
      "condenser",
      "supercardioid",
      "vocal",
      "microphone",
    ],
    powerDrawW: 0,
    heightMm: 192,
    widthMm: 51,
    depthMm: 51,
    weightKg: 0.2,
    ports: [port("XLR Out", "analog-audio", "output", "xlr-3")],
  },
  // ── Shure MX412 ──────────────────────────────────────────────────
  {
    id: "c0a80101-01b3-4000-8000-000000000435",
    deviceType: "wired-mic",
    label: "Shure MX412",
    manufacturer: "Shure",
    modelNumber: "MX412",
    referenceUrl:
      "https://www.shure.com/en-US/products/microphones/mx412",
    searchTerms: [
      "shure",
      "mx412",
      "gooseneck",
      "condenser",
      "microflex",
      "podium",
    ],
    powerDrawW: 0,
    heightMm: 331,
    widthMm: 12,
    depthMm: 12,
    weightKg: 0.2,
    ports: [port("XLR Out", "analog-audio", "output", "xlr-3")],
  },
  // ── Shure MX418 ──────────────────────────────────────────────────
  {
    id: "c0a80101-01b4-4000-8000-000000000436",
    deviceType: "wired-mic",
    label: "Shure MX418",
    manufacturer: "Shure",
    modelNumber: "MX418",
    referenceUrl:
      "https://www.shure.com/en-US/products/microphones/mx418",
    searchTerms: [
      "shure",
      "mx418",
      "gooseneck",
      "condenser",
      "microflex",
      "podium",
      "18 inch",
    ],
    powerDrawW: 0,
    heightMm: 483,
    widthMm: 12,
    depthMm: 12,
    weightKg: 0.2,
    ports: [port("XLR Out", "analog-audio", "output", "xlr-3")],
  },
];
