import { port, ports } from "./_helpers";
import type { DeviceTemplate } from "../types";

export const templates: DeviceTemplate[] = [
  // VFC Expansion Cards (for Disguise VX/GX series)
  {
    id: "vfc-card-hdmi20",
    deviceType: "expansion-card",
    slotFamily: "disguise-vfc",
    label: "HDMI 2.0 VFC",
    manufacturer: "Disguise",
    modelNumber: "HDMI 2.0 VFC",
    referenceUrl: "https://www.disguise.one/en/products/vfc-cards/",
    searchTerms: ["vfc", "hdmi", "output", "disguise"],
    ports: [
      port("HDMI Out", "hdmi", "output"),
    ],
  },
  {
    id: "vfc-card-dp14",
    deviceType: "expansion-card",
    slotFamily: "disguise-vfc",
    label: "DisplayPort 1.4 VFC",
    manufacturer: "Disguise",
    modelNumber: "DisplayPort 1.4 VFC",
    referenceUrl: "https://www.disguise.one/en/products/vfc-cards/",
    searchTerms: ["vfc", "displayport", "dp14", "output", "disguise"],
    ports: [
      port("DP Out", "displayport", "output"),
    ],
  },
  {
    id: "vfc-card-dp12",
    deviceType: "expansion-card",
    slotFamily: "disguise-vfc",
    label: "DisplayPort 1.2 VFC",
    manufacturer: "Disguise",
    modelNumber: "DisplayPort 1.2 VFC",
    referenceUrl: "https://www.disguise.one/en/products/vfc-cards/",
    searchTerms: ["vfc", "displayport", "dp12", "output", "disguise"],
    ports: [
      port("DP Out", "displayport", "output"),
    ],
  },
  {
    id: "vfc-card-quad-sdi",
    deviceType: "expansion-card",
    slotFamily: "disguise-vfc",
    label: "Quad SDI VFC",
    manufacturer: "Disguise",
    modelNumber: "Quad SDI VFC",
    referenceUrl: "https://www.disguise.one/en/products/vfc-cards/",
    searchTerms: ["vfc", "sdi", "quad", "output", "disguise"],
    ports: [
      ...ports("SDI Out", "sdi", "output", 4, "bnc"),
    ],
  },
  {
    id: "vfc-card-quad-dvi",
    deviceType: "expansion-card",
    slotFamily: "disguise-vfc",
    label: "Quad DVI VFC",
    manufacturer: "Disguise",
    modelNumber: "Quad DVI VFC",
    referenceUrl: "https://www.disguise.one/en/products/vfc-cards/",
    searchTerms: ["vfc", "dvi", "quad", "output", "disguise"],
    ports: [
      ...ports("DVI Out", "hdmi", "output", 4, "dvi"),
    ],
  },
  {
    id: "vfc-card-ip",
    deviceType: "expansion-card",
    slotFamily: "disguise-vfc",
    label: "IP-VFC",
    manufacturer: "Disguise",
    modelNumber: "IP-VFC",
    referenceUrl: "https://www.disguise.one/en/products/vfc-cards/",
    searchTerms: ["vfc", "ip", "sfp28", "output", "disguise"],
    slots: [
      { id: "vfc-ip-sfp-1", label: "SFP28 1", slotFamily: "sfp", defaultCardId: "sfp-25g-sr" },
      { id: "vfc-ip-sfp-2", label: "SFP28 2", slotFamily: "sfp", defaultCardId: "sfp-25g-sr" },
      { id: "vfc-ip-sfp-3", label: "SFP28 3", slotFamily: "sfp", defaultCardId: "sfp-25g-sr" },
      { id: "vfc-ip-sfp-4", label: "SFP28 4", slotFamily: "sfp", defaultCardId: "sfp-25g-sr" },
    ],
    ports: [],
  },
  // Barco Event Master I/O Cards
  {
    id: "barco-em-tricombo-in",
    deviceType: "expansion-card",
    slotFamily: "barco-em-input",
    label: "4K Tri-Combo Input",
    manufacturer: "Barco",
    modelNumber: "4K Tri-Combo Input",
    referenceUrl: "https://www.barco.com/en/products/image-processing/event-master",
    searchTerms: ["barco", "event master", "tri-combo", "input", "card"],
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("DP In", "displayport", "input"),
      ...ports("SDI In", "sdi", "input", 4, "bnc"),
    ],
  },
  {
    id: "barco-em-tricombo-out",
    deviceType: "expansion-card",
    slotFamily: "barco-em-output",
    label: "4K Tri-Combo Output",
    manufacturer: "Barco",
    modelNumber: "4K Tri-Combo Output",
    referenceUrl: "https://www.barco.com/en/products/image-processing/event-master",
    searchTerms: ["barco", "event master", "tri-combo", "output", "card"],
    ports: [
      port("HDMI Out", "hdmi", "output"),
      port("DP Out", "displayport", "output"),
      ...ports("SDI Out", "sdi", "output", 4, "bnc"),
    ],
  },
  {
    id: "barco-em-hdmi-quad-in",
    deviceType: "expansion-card",
    slotFamily: "barco-em-input",
    label: "HDMI 2.0 Quad Input",
    manufacturer: "Barco",
    modelNumber: "HDMI 2.0 Quad Input",
    referenceUrl: "https://www.barco.com/en/products/image-processing/event-master",
    searchTerms: ["barco", "event master", "hdmi", "quad", "input", "card"],
    ports: [
      ...ports("HDMI In", "hdmi", "input", 4),
    ],
  },
  {
    id: "barco-em-hdmi-quad-out",
    deviceType: "expansion-card",
    slotFamily: "barco-em-output",
    label: "HDMI 2.0 Quad Output",
    manufacturer: "Barco",
    modelNumber: "HDMI 2.0 Quad Output",
    referenceUrl: "https://www.barco.com/en/products/image-processing/event-master",
    searchTerms: ["barco", "event master", "hdmi", "quad", "output", "card"],
    ports: [
      ...ports("HDMI Out", "hdmi", "output", 4),
    ],
  },
  {
    id: "barco-em-dp-quad-in",
    deviceType: "expansion-card",
    slotFamily: "barco-em-input",
    label: "DP 1.2 Quad Input",
    manufacturer: "Barco",
    modelNumber: "DP 1.2 Quad Input",
    referenceUrl: "https://www.barco.com/en/products/image-processing/event-master",
    searchTerms: ["barco", "event master", "displayport", "quad", "input", "card"],
    ports: [
      ...ports("DP In", "displayport", "input", 4),
    ],
  },
  {
    id: "barco-em-dp-quad-out",
    deviceType: "expansion-card",
    slotFamily: "barco-em-output",
    label: "DP 1.2 Quad Output",
    manufacturer: "Barco",
    modelNumber: "DP 1.2 Quad Output",
    referenceUrl: "https://www.barco.com/en/products/image-processing/event-master",
    searchTerms: ["barco", "event master", "displayport", "quad", "output", "card"],
    ports: [
      ...ports("DP Out", "displayport", "output", 4),
    ],
  },
  // Analog Way Aquilon I/O Modules
  {
    id: "aw-aql-in-dp",
    deviceType: "expansion-card",
    slotFamily: "aw-aql-input",
    label: "Aquilon DP Input Module",
    manufacturer: "Analog Way",
    modelNumber: "Aquilon DP Input Module",
    referenceUrl: "https://www.analogway.com/products/four-displayport-1-2-input-card-for-livepremier-tm-series",
    searchTerms: ["analog way", "aquilon", "displayport", "input", "module"],
    ports: [
      ...ports("DP In", "displayport", "input", 4),
    ],
  },
  {
    id: "aw-aql-in-sdi",
    deviceType: "expansion-card",
    slotFamily: "aw-aql-input",
    label: "Aquilon SDI Input Module",
    manufacturer: "Analog Way",
    modelNumber: "Aquilon SDI Input Module",
    referenceUrl: "https://www.analogway.com/products/four-12g-sdi-input-card-for-livepremier-tm-series",
    searchTerms: ["analog way", "aquilon", "sdi", "input", "module"],
    ports: [
      ...ports("SDI In", "sdi", "input", 4, "bnc"),
    ],
  },
  {
    id: "aw-aql-out-sdi",
    deviceType: "expansion-card",
    slotFamily: "aw-aql-output",
    label: "Aquilon SDI Output Module",
    manufacturer: "Analog Way",
    modelNumber: "Aquilon SDI Output Module",
    referenceUrl: "https://www.analogway.com/products/four-12g-sdi-output-card-for-livepremier-tm-series",
    searchTerms: ["analog way", "aquilon", "sdi", "output", "module"],
    ports: [
      ...ports("SDI Out", "sdi", "output", 4, "bnc"),
    ],
  },
  // Yamaha MY Card System
  {
    id: "yamaha-my8-ae",
    deviceType: "expansion-card",
    slotFamily: "yamaha-my",
    label: "MY8-AE",
    manufacturer: "Yamaha",
    modelNumber: "MY8-AE",
    referenceUrl: "https://usa.yamaha.com/products/proaudio/interfaces/digital_cards/index.html",
    searchTerms: ["yamaha", "my8", "aes", "expansion", "card"],
    heightMm: 40,
    widthMm: 120,
    depthMm: 176,
    ports: [
      ...ports("AES In", "aes", "input", 8),
      ...ports("AES Out", "aes", "output", 8),
    ],
  },
  {
    id: "yamaha-my16-ae",
    deviceType: "expansion-card",
    slotFamily: "yamaha-my",
    label: "MY16-AE",
    manufacturer: "Yamaha",
    modelNumber: "MY16-AE",
    referenceUrl: "https://usa.yamaha.com/products/proaudio/interfaces/digital_cards/index.html",
    searchTerms: ["yamaha", "my16", "aes", "expansion", "card"],
    heightMm: 40,
    widthMm: 120,
    depthMm: 176,
    ports: [
      ...ports("AES In", "aes", "input", 16),
      ...ports("AES Out", "aes", "output", 16),
    ],
  },
  {
    id: "yamaha-my8-lake",
    deviceType: "expansion-card",
    slotFamily: "yamaha-my",
    label: "MY8-LAKE",
    manufacturer: "Yamaha",
    modelNumber: "MY8-LAKE",
    referenceUrl: "https://usa.yamaha.com/products/proaudio/interfaces/my8-lake/index.html",
    searchTerms: ["yamaha", "my8", "lake", "processing", "expansion", "card"],
    heightMm: 40,
    widthMm: 120,
    depthMm: 176,
    ports: [
      ...ports("AES In", "aes", "input", 8),
      ...ports("AES Out", "aes", "output", 8),
      port("Ethernet", "ethernet", "bidirectional", "rj45"),
    ],
  },
  {
    id: "yamaha-dugan-my16",
    deviceType: "expansion-card",
    slotFamily: "yamaha-my",
    label: "Dugan-MY16",
    manufacturer: "Yamaha",
    modelNumber: "Dugan-MY16",
    referenceUrl: "https://usa.yamaha.com/products/proaudio/interfaces/dugan-my16/index.html",
    searchTerms: ["yamaha", "dugan", "auto-mix", "expansion", "card"],
    heightMm: 40,
    widthMm: 120,
    depthMm: 176,
    weightKg: 0.2,
    ports: [
      port("ADAT 1", "adat", "bidirectional"),
      port("ADAT 2", "adat", "bidirectional"),
    ],
  },
  // DiGiCo DMI Cards
  {
    id: "digico-dmi-dante",
    deviceType: "expansion-card",
    slotFamily: "digico-dmi",
    label: "DMI-Dante",
    manufacturer: "DiGiCo",
    modelNumber: "DMI-Dante",
    referenceUrl: "https://digico.biz/dmi_cards/dmi-dante64/",
    searchTerms: ["digico", "dmi", "dante", "expansion", "card"],
    heightMm: 58,
    widthMm: 126,
    depthMm: 176,
    ports: [
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
    ],
  },
  {
    id: "digico-dmi-madi",
    deviceType: "expansion-card",
    slotFamily: "digico-dmi",
    label: "DMI-MADI",
    manufacturer: "DiGiCo",
    modelNumber: "DMI-MADI",
    referenceUrl: "https://digico.biz/dmi_cards/dmi-madi-b/",
    searchTerms: ["digico", "dmi", "madi", "expansion", "card"],
    heightMm: 58,
    widthMm: 126,
    depthMm: 176,
    weightKg: 0.3,
    ports: [
      port("MADI 1", "madi", "bidirectional"),
      port("MADI 2", "madi", "bidirectional"),
    ],
  },
  {
    id: "digico-dmi-waves",
    deviceType: "expansion-card",
    slotFamily: "digico-dmi",
    label: "DMI-Waves",
    manufacturer: "DiGiCo",
    modelNumber: "DMI-Waves",
    referenceUrl: "https://digico.biz/dmi_cards/",
    searchTerms: ["digico", "dmi", "waves", "soundgrid", "expansion", "card"],
    heightMm: 58,
    widthMm: 126,
    depthMm: 176,
    ports: [
      port("Ethernet", "ethernet", "bidirectional"),
    ],
  },
  // Barco Event Master — SDI Quad Cards
  {
    id: "barco-em-sdi-quad-in",
    deviceType: "expansion-card",
    slotFamily: "barco-em-input",
    label: "SDI Quad Input",
    manufacturer: "Barco",
    modelNumber: "SDI Quad Input",
    referenceUrl: "https://www.barco.com/en/products/image-processing/event-master",
    searchTerms: ["barco", "event master", "sdi", "quad", "input", "card"],
    ports: [
      ...ports("SDI In", "sdi", "input", 4, "bnc"),
    ],
  },
  {
    id: "barco-em-sdi-quad-out",
    deviceType: "expansion-card",
    slotFamily: "barco-em-output",
    label: "SDI Quad Output",
    manufacturer: "Barco",
    modelNumber: "SDI Quad Output",
    referenceUrl: "https://www.barco.com/en/products/image-processing/event-master",
    searchTerms: ["barco", "event master", "sdi", "quad", "output", "card"],
    ports: [
      ...ports("SDI Out", "sdi", "output", 4, "bnc"),
    ],
  },
  // Analog Way Aquilon — Additional Modules
  {
    id: "aw-aql-in-hdmi",
    deviceType: "expansion-card",
    slotFamily: "aw-aql-input",
    label: "Aquilon HDMI Input Module",
    manufacturer: "Analog Way",
    modelNumber: "Aquilon HDMI Input Module",
    referenceUrl: "https://www.analogway.com/emea/products/midra-range/aquilon-c/",
    searchTerms: ["analog way", "aquilon", "hdmi", "input", "module"],
    ports: [
      ...ports("HDMI In", "hdmi", "input", 4),
    ],
  },
  {
    id: "aw-aql-out-hdmi",
    deviceType: "expansion-card",
    slotFamily: "aw-aql-output",
    label: "Aquilon HDMI Output Module",
    manufacturer: "Analog Way",
    modelNumber: "Aquilon HDMI Output Module",
    referenceUrl: "https://www.analogway.com/emea/products/midra-range/aquilon-c/",
    searchTerms: ["analog way", "aquilon", "hdmi", "output", "module"],
    ports: [
      ...ports("HDMI Out", "hdmi", "output", 4),
    ],
  },
  {
    id: "aw-aql-out-dp",
    deviceType: "expansion-card",
    slotFamily: "aw-aql-output",
    label: "Aquilon DP Output Module",
    manufacturer: "Analog Way",
    modelNumber: "Aquilon DP Output Module",
    referenceUrl: "https://www.analogway.com/emea/products/midra-range/aquilon-c/",
    searchTerms: ["analog way", "aquilon", "displayport", "output", "module"],
    ports: [
      ...ports("DP Out", "displayport", "output", 4),
    ],
  },
  {
    id: "aw-aql-in-fiber",
    deviceType: "expansion-card",
    slotFamily: "aw-aql-input",
    label: "Aquilon Fiber Input Module",
    manufacturer: "Analog Way",
    modelNumber: "Aquilon Fiber Input Module",
    referenceUrl: "https://www.analogway.com/emea/products/midra-range/aquilon-c/",
    searchTerms: ["analog way", "aquilon", "fiber", "input", "module"],
    ports: [
      ...ports("Fiber In", "fiber", "input", 4, "sc"),
    ],
  },
  {
    id: "aw-aql-out-fiber",
    deviceType: "expansion-card",
    slotFamily: "aw-aql-output",
    label: "Aquilon Fiber Output Module",
    manufacturer: "Analog Way",
    modelNumber: "Aquilon Fiber Output Module",
    referenceUrl: "https://www.analogway.com/emea/products/midra-range/aquilon-c/",
    searchTerms: ["analog way", "aquilon", "fiber", "output", "module"],
    ports: [
      ...ports("Fiber Out", "fiber", "output", 4, "sc"),
    ],
  },
  // Crestron DM Input/Output Cards
  {
    id: "crestron-dmc-4kz-hd",
    deviceType: "expansion-card",
    slotFamily: "crestron-dm-input",
    label: "DMC-4KZ-HD",
    manufacturer: "Crestron",
    modelNumber: "DMC-4KZ-HD",
    referenceUrl: "https://www.crestron.com/Products/Catalog/DigitalMedia/DM-Digital-Media-Switchers",
    searchTerms: ["crestron", "dmc", "4kz", "hdmi", "hdbaset", "input", "card"],
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("HDBaseT In", "hdbaset", "input"),
    ],
  },
  {
    id: "crestron-dmc-4kz-hdmi",
    deviceType: "expansion-card",
    slotFamily: "crestron-dm-input",
    label: "DMC-4KZ-HDMI",
    manufacturer: "Crestron",
    modelNumber: "DMC-4KZ-HDMI",
    referenceUrl: "https://www.crestron.com/Products/Catalog/DigitalMedia/DM-Digital-Media-Switchers",
    searchTerms: ["crestron", "dmc", "4kz", "hdmi", "dual", "input", "card"],
    ports: [
      ...ports("HDMI In", "hdmi", "input", 2),
    ],
  },
  {
    id: "crestron-dmc-4kz-c",
    deviceType: "expansion-card",
    slotFamily: "crestron-dm-input",
    label: "DMC-4KZ-C",
    manufacturer: "Crestron",
    modelNumber: "DMC-4KZ-C",
    referenceUrl: "https://www.crestron.com/Products/Catalog/DigitalMedia/DM-Digital-Media-Switchers",
    searchTerms: ["crestron", "dmc", "4kz", "hdmi", "hdbaset", "input", "card"],
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("HDBaseT In", "hdbaset", "input"),
    ],
  },
  {
    id: "crestron-dmco-4kz-hd",
    deviceType: "expansion-card",
    slotFamily: "crestron-dm-output",
    label: "DMCO-4KZ-HD",
    manufacturer: "Crestron",
    modelNumber: "DMCO-4KZ-HD",
    referenceUrl: "https://www.crestron.com/Products/Catalog/DigitalMedia/DM-Digital-Media-Switchers",
    searchTerms: ["crestron", "dmco", "4kz", "hdmi", "hdbaset", "output", "card"],
    ports: [
      port("HDMI Out", "hdmi", "output"),
      port("HDBaseT Out", "hdbaset", "output"),
    ],
  },
  {
    id: "crestron-dmco-4kz-hdmi",
    deviceType: "expansion-card",
    slotFamily: "crestron-dm-output",
    label: "DMCO-4KZ-HDMI",
    manufacturer: "Crestron",
    modelNumber: "DMCO-4KZ-HDMI",
    referenceUrl: "https://www.crestron.com/Products/Catalog/DigitalMedia/DM-Digital-Media-Switchers",
    searchTerms: ["crestron", "dmco", "4kz", "hdmi", "dual", "output", "card"],
    ports: [
      ...ports("HDMI Out", "hdmi", "output", 2),
    ],
  },
  // Lightware MX2M Input/Output Boards
  {
    id: "lightware-mx2m-hdmi-ib",
    deviceType: "expansion-card",
    slotFamily: "lightware-mx2m-video-in",
    label: "MX2M HDMI Input Board",
    manufacturer: "Lightware",
    modelNumber: "MX2M HDMI Input Board",
    referenceUrl: "https://lightware.com/product-families/mx-series",
    searchTerms: ["lightware", "mx2m", "hdmi", "input", "board"],
    ports: [
      ...ports("HDMI In", "hdmi", "input", 4),
    ],
  },
  {
    id: "lightware-mx2m-hdmi-ob",
    deviceType: "expansion-card",
    slotFamily: "lightware-mx2m-video-out",
    label: "MX2M HDMI Output Board",
    manufacturer: "Lightware",
    modelNumber: "MX2M HDMI Output Board",
    referenceUrl: "https://lightware.com/product-families/mx-series",
    searchTerms: ["lightware", "mx2m", "hdmi", "output", "board"],
    ports: [
      ...ports("HDMI Out", "hdmi", "output", 4),
    ],
  },
  {
    id: "lightware-mx2m-dp-ib",
    deviceType: "expansion-card",
    slotFamily: "lightware-mx2m-video-in",
    label: "MX2M DP Input Board",
    manufacturer: "Lightware",
    modelNumber: "MX2M DP Input Board",
    referenceUrl: "https://lightware.com/product-families/mx-series",
    searchTerms: ["lightware", "mx2m", "displayport", "input", "board"],
    ports: [
      ...ports("DP In", "displayport", "input", 4),
    ],
  },
  {
    id: "lightware-mx2m-fiber-ib",
    deviceType: "expansion-card",
    slotFamily: "lightware-mx2m-video-in",
    label: "MX2M Fiber Input Board",
    manufacturer: "Lightware",
    modelNumber: "MX2M Fiber Input Board",
    referenceUrl: "https://lightware.com/product-families/mx-series",
    searchTerms: ["lightware", "mx2m", "fiber", "input", "board"],
    ports: [
      ...ports("Fiber In", "fiber", "input", 4, "sc"),
    ],
  },
  {
    id: "lightware-mx2m-fiber-ob",
    deviceType: "expansion-card",
    slotFamily: "lightware-mx2m-video-out",
    label: "MX2M Fiber Output Board",
    manufacturer: "Lightware",
    modelNumber: "MX2M Fiber Output Board",
    referenceUrl: "https://lightware.com/product-families/mx-series",
    searchTerms: ["lightware", "mx2m", "fiber", "output", "board"],
    ports: [
      ...ports("Fiber Out", "fiber", "output", 4, "sc"),
    ],
  },
  // Yamaha MY — Additional Cards
  {
    id: "yamaha-my16-md64",
    deviceType: "expansion-card",
    slotFamily: "yamaha-my",
    label: "MY16-MD64",
    manufacturer: "Yamaha",
    modelNumber: "MY16-MD64",
    referenceUrl: "https://usa.yamaha.com/products/proaudio/interfaces/digital_cards/index.html",
    searchTerms: ["yamaha", "my16", "madi", "expansion", "card"],
    heightMm: 40,
    widthMm: 120,
    depthMm: 176,
    weightKg: 0.5,
    ports: [
      port("MADI In", "madi", "input", "bnc"),
      port("MADI Out", "madi", "output", "bnc"),
    ],
  },
  {
    id: "yamaha-my16-at",
    deviceType: "expansion-card",
    slotFamily: "yamaha-my",
    label: "MY16-AT",
    manufacturer: "Yamaha",
    modelNumber: "MY16-AT",
    referenceUrl: "https://usa.yamaha.com/products/proaudio/interfaces/digital_cards/index.html",
    searchTerms: ["yamaha", "my16", "adat", "expansion", "card"],
    heightMm: 40,
    widthMm: 120,
    depthMm: 176,
    ports: [
      ...ports("ADAT In", "adat", "input", 2),
      ...ports("ADAT Out", "adat", "output", 2),
    ],
  },
  // Allen & Heath dLive I/O Cards
  {
    id: "ah-dlive-dante128",
    deviceType: "expansion-card",
    slotFamily: "ah-dlive-io",
    label: "M-DL-DANTE128",
    manufacturer: "Allen & Heath",
    modelNumber: "M-DL-DANTE128",
    referenceUrl: "https://www.allen-heath.com/hardware/dlive-series/",
    searchTerms: ["allen heath", "dlive", "dante", "128", "expansion", "card"],
    ports: [
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
    ],
  },
  {
    id: "ah-dlive-madi",
    deviceType: "expansion-card",
    slotFamily: "ah-dlive-io",
    label: "M-DL-SMADI",
    manufacturer: "Allen & Heath",
    modelNumber: "M-DL-SMADI",
    referenceUrl: "https://www.allen-heath.com/hardware/dlive-series/",
    searchTerms: ["allen heath", "dlive", "madi", "expansion", "card"],
    ports: [
      port("MADI 1", "madi", "bidirectional"),
      port("MADI 2", "madi", "bidirectional"),
    ],
  },
  {
    id: "ah-dlive-waves",
    deviceType: "expansion-card",
    slotFamily: "ah-dlive-io",
    label: "M-DL-WAVES3",
    manufacturer: "Allen & Heath",
    modelNumber: "M-DL-WAVES3",
    referenceUrl: "https://www.allen-heath.com/hardware/dlive-series/",
    searchTerms: ["allen heath", "dlive", "waves", "soundgrid", "expansion", "card"],
    ports: [
      port("Ethernet", "ethernet", "bidirectional"),
    ],
  },
  // Allen & Heath SQ SLink Card
  {
    id: "ah-sq-slink-card",
    version: 2, // v2: SLink port signal corrected fiber → slink
    deviceType: "expansion-card",
    slotFamily: "ah-sq-slink",
    label: "SQ SLink Card",
    manufacturer: "Allen & Heath",
    modelNumber: "SQ SLink Card",
    referenceUrl: "https://www.allen-heath.com/hardware/audio-networking/sq-slink/",
    searchTerms: ["allen heath", "sq", "slink", "expansion", "card"],
    ports: [
      port("SLink", "slink", "bidirectional"),
    ],
  },
  // Ross Ultrix I/O Cards
  {
    id: "ross-ultrix-hdx-io",
    deviceType: "expansion-card",
    slotFamily: "ross-ultrix",
    label: "ULTRIX-HDX-IO",
    manufacturer: "Ross Video",
    modelNumber: "ULTRIX-HDX-IO",
    referenceUrl: "https://www.rossvideo.com/products/routing-systems/ultrix/ultrix-specifications/",
    searchTerms: ["ross", "ultrix", "hdx", "sdi", "12g", "expansion", "card"],
    ports: [
      ...ports("SDI In", "sdi", "input", 16, "bnc"),
      ...ports("SDI Out", "sdi", "output", 16, "bnc"),
    ],
  },
  {
    id: "ross-ultrix-ipx-io",
    deviceType: "expansion-card",
    slotFamily: "ross-ultrix",
    label: "ULTRIX-IPX-IO",
    manufacturer: "Ross Video",
    modelNumber: "ULTRIX-IPX-IO",
    referenceUrl: "https://www.rossvideo.com/products/routing-systems/ultrix/ultrix-specifications/",
    searchTerms: ["ross", "ultrix", "ipx", "ip", "st2110", "qsfp28", "expansion", "card"],
    slots: [
      { id: "ultrix-ipx-qsfp-1", label: "QSFP28 1", slotFamily: "qsfp", defaultCardId: "qsfp-40g-sr4" },
      { id: "ultrix-ipx-qsfp-2", label: "QSFP28 2", slotFamily: "qsfp", defaultCardId: "qsfp-40g-sr4" },
      { id: "ultrix-ipx-qsfp-3", label: "QSFP28 3", slotFamily: "qsfp", defaultCardId: "qsfp-40g-sr4" },
      { id: "ultrix-ipx-qsfp-4", label: "QSFP28 4", slotFamily: "qsfp", defaultCardId: "qsfp-40g-sr4" },
    ],
    ports: [],
  },

  // Active Accessory Adapters (plug into a host's accessory port and add wireless / control I/O)
  {
    id: "zoom-bta1",
    deviceType: "expansion-card",
    slotFamily: "zoom-bta-port",
    label: "Zoom BTA-1 Bluetooth Adapter",
    manufacturer: "Zoom",
    modelNumber: "BTA-1",
    referenceUrl: "https://zoomcorp.com/en/us/accessories/power-accessories/BTA-1/",
    searchTerms: ["zoom", "bta-1", "bluetooth", "timecode", "wireless", "remote", "f6", "ultrasync"],
    unitCost: 40,
    ports: [
      port("Bluetooth Control", "bluetooth", "bidirectional", "wireless"),
      port("Wireless Timecode", "timecode", "input", "wireless"),
    ],
  },
];
